  services:
    db:
      container_name: tulisaja-mariadb
      image: mariadb
      restart: always
      environment:
        MARIADB_ROOT_PASSWORD: asdf1234
      volumes:
        - ./db-data:/var/lib/mysql
      ports:
        - 3306:3306

    adminer:
      container_name: tulisaja-adminer
      image: adminer
      restart: always
      ports:
        - 7070:8080
      depends_on:
        - db